[package]
name = "datagen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.2"
chrono = "0.4.23"
serde_json = "1.0.68"
rayon = "1.5"
